<?php

namespace App\Http\Requests\Cart;

use App\Http\Requests\BaseRequest;

class AddToCartRequest extends BaseRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules(): array
    {
        return [
            'id'                  => 'required|exists:products,id',
            'productName'         => 'required|string',
            'productVariantValue' => 'string',
            'productImage'        => 'required|string',
            'currentPrice'        => 'required|numeric|min:0',
            'cartQuantity'        => 'required|min:1',
        ];
    }

    public function attributes(): array
    {
        return [
            'id'                  => 'Product id',
            'productName'         => 'Product name',
            'productVariantValue' => 'Variant value',
            'productImage'       => 'Thumbnail',
            'currentPrice'        => 'Price',
            'cartQuantity'        => 'Quantity'
        ]; // TODO: Change the autogenerated stub
    }

    public function messages(): array
    {
        return [
            'required' => 'The :attribute field is required.',
            'exists'   => 'Product is not exists.',
            'integer'  => 'The :attribute must be an integer.',
            'min'      => 'Minimum quantity is 1'
        ]; // TODO: Change the autogenerated stub
    }
}
