<?php

namespace App\Http\Requests\Cart;

use App\Http\Requests\BaseRequest;
use Illuminate\Foundation\Http\FormRequest;

class CartRequestUpdate extends BaseRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules(): array
    {
        return [
            'quantity'   => 'required|numeric|min:0|max:50',
        ];
    }

    public function attributes(): array
    {
        return [
            'quantity'   => 'Quantity'
        ]; // TODO: Change the autogenerated stub
    }

    public function messages(): array
    {
        return [
            'required' => 'The :attribute field is required.',
            'numeric' => 'The :attribute must be a number.',
            'min' => 'The :attribute must be at least 0.',
            'max' => 'The :attribute max :max item',
        ]; // TODO: Change the autogenerated stub
    }
}
